In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
X = np.array([[0,0],
            [1,0],
            [2,2],
            [0,1],
            [1,1],
            [2,3],
            [0,2],
            [1,2],
            [2,0],
            [2,1]])

In [4]:
Y = np.array([[1],
            [3],
            [11],
            [4],
            [6],
            [14],
            [7],
            [9],
            [5],
            [8]])

In [5]:
def MR_create_Xb(X):
    N = X.shape[0]
    ones = np.ones([N, 1])
    Xb = np.hstack([ones, X])
    return Xb

In [11]:
def MR_find_W_local(X, Y, epoch = 1000, lr = 0.1):
    Xb = MR_create_Xb(X)
    N = Xb.shape[0]
    #D_1 = Xb.shape[1]
    #W = np.random.randn(D_1, 1)
    W = np.array([[0.3],[0.4],[0.5]])
    print(0)
    print(W)
    print()
    error_list = []
    for i in range(epoch):
        print(i+1)
        #Yhat = MR_find_Yhat(X, W)
        #error = find_error(Y, Yhat, 'SSE')
        #error_list.append(error)
        #S = np.dot(Xb.T, Y - Yhat)
        #W = W + (lr/N)*S
        Yhat = np.dot(Xb, W)
        W = W + (lr/N)*np.dot(Xb.T, Y-Yhat)
        print(W)
        print()
    return W, error_list

In [12]:
 MR_find_W_local(X, Y, epoch = 1000, lr = 0.1)

0
[[0.3]
 [0.4]
 [0.5]]

1
[[0.846]
 [1.156]
 [1.424]]

2
[[1.14336]
 [1.5697 ]
 [1.94732]]

3
[[1.3026786]
 [1.7935894]
 [2.247305 ]]

4
[[1.38543931]
 [1.91241702]
 [2.42259196]]

5
[[1.42581847]
 [1.97327067]
 [2.52805462]]

6
[[1.44281029]
 [2.00230102]
 [2.59423269]]

7
[[1.44696823]
 [2.01401979]
 [2.63813446]]

8
[[1.44415309]
 [2.01646935]
 [2.66924303]]

9
[[1.43761699]
 [2.01409688]
 [2.69285593]]

10
[[1.42916192]
 [2.00935221]
 [2.71194194]]

11
[[1.41978396]
 [2.00357619]
 [2.72817361]]

12
[[1.41003135]
 [1.99749444]
 [2.74250144]]

13
[[1.40020365]
 [1.99149183]
 [2.75547317]]

14
[[1.3904624 ]
 [1.98576501]
 [2.76741139]]

15
[[1.38089265]
 [1.98040708]
 [2.77851242]]

16
[[1.37153711]
 [1.97545468]
 [2.78890126]]

17
[[1.36241523]
 [1.97091402]
 [2.7986623 ]]

18
[[1.35353369]
 [1.96677534]
 [2.80785642]]

19
[[1.34489227]
 [1.96302085]
 [2.81653053]]

20
[[1.33648708]
 [1.95962916]
 [2.82472301]]

21
[[1.32831241]
 [1.95657759]
 [2.83246666]]

22
[[1.32036163]
 [1.953

 [2.99999961]]

566
[[1.00000146]
 [1.99999938]
 [2.99999962]]

567
[[1.00000143]
 [1.99999939]
 [2.99999963]]

568
[[1.0000014 ]
 [1.99999941]
 [2.99999964]]

569
[[1.00000137]
 [1.99999942]
 [2.99999965]]

570
[[1.00000134]
 [1.99999943]
 [2.99999965]]

571
[[1.00000131]
 [1.99999944]
 [2.99999966]]

572
[[1.00000128]
 [1.99999946]
 [2.99999967]]

573
[[1.00000125]
 [1.99999947]
 [2.99999968]]

574
[[1.00000122]
 [1.99999948]
 [2.99999968]]

575
[[1.0000012 ]
 [1.99999949]
 [2.99999969]]

576
[[1.00000117]
 [1.9999995 ]
 [2.9999997 ]]

577
[[1.00000114]
 [1.99999951]
 [2.9999997 ]]

578
[[1.00000112]
 [1.99999953]
 [2.99999971]]

579
[[1.00000109]
 [1.99999954]
 [2.99999972]]

580
[[1.00000107]
 [1.99999955]
 [2.99999972]]

581
[[1.00000104]
 [1.99999956]
 [2.99999973]]

582
[[1.00000102]
 [1.99999957]
 [2.99999974]]

583
[[1.000001  ]
 [1.99999958]
 [2.99999974]]

584
[[1.00000098]
 [1.99999959]
 [2.99999975]]

585
[[1.00000095]
 [1.99999959]
 [2.99999975]]

586
[[1.00000093]
 [1.99

(array([[1.],
        [2.],
        [3.]]), [])

In [ ]:
#############################

In [4]:
X = np.array([[7,0,5],
            [9,4,2],
            [2,6,3]])

In [5]:
X.min(axis=0)

array([2, 0, 2])

In [6]:
X.min(axis=1)

array([0, 2, 2])

In [10]:
min_reshape = X.min(axis=0)
min_reshape.reshape(1,-1)

array([[2, 0, 2]])